use_frameworks!

platform :ios, '13.0'

target 'SSNaturalLanguage_Example' do
  pod 'SSNaturalLanguage', :path => '../'

  target 'SSNaturalLanguage_Tests' do
    inherit! :search_paths

    
  end
end
